### PR TITLE
Fixes #4037

### LINKED ISSUE #4037: Strange issue on node webkit
- rethinkdb 1.16.3
- rethinkdb.js 1.16.2
- nw.js 0.12.0

I'm attempting to run this query in node webkit:

`test.js`:

```js
var r = require('rethinkdb');
var conn;

r.connect().then(function (connection) {
  conn = connection;
  return r.db('rethinkdb')
          .table('table_config', { identifier_format: 'uuid' })
          .eqJoin('id', r.db('rethinkdb').table('table_status', { identifier_format: 'uuid' }))
          .zip()
          .map(function (table) {
           return table.merge(function (table) {
             return {
               shards: table('shards').map(function (shard) {
                 return shard.merge(function (shard) {
                   return {
                     replicas: shard('replicas').innerJoin(
                       r.db('rethinkdb')
                         .table('stats', { identifier_format: 'uuid' })
                         .filter(function (stat) {
                            return stat('table').eq(table('id')).and(stat.hasFields('storage_engine'));
                          })
                         .without('id', 'table', 'db'),
                       function (replicaRow, statRow) {
                        return replicaRow('server').eq(statRow('server'));
                      }
                     ).zip().coerceTo('array')
                   };
                 });
               }).coerceTo('array')
             };
           });
          })
          .coerceTo('array')
          .run(connection);
}).then(function (tables) {
  console.log(tables);
}).catch(function (err) {
  console.error(err);
}).finally(function () {
  if (conn) {
    conn.close();
  }
});
```

It runs fine in the web console and when I just run `node test.js`. When executed from node webkit it fails with the following error:

```
Unhandled rejection RqlRuntimeError: Expected type FUNCTION but found DATUM:
null in:
r.db("rethinkdb").table("table_config", {identifierFormat: "uuid"}).eqJoin("id", r.db("rethinkdb").table("table_status", {identifierFormat: "uuid"})).zip().map(function (table) {
        return table.merge(function (table) {
          return {
            shards: table('shards').map(function (shard) {
              return shard.merge(function (shard) {
                return {
                  replicas: shard('replicas').innerJoin(r.db('rethinkdb').table('stats', { identifier_format: 'uuid' }).filter(function (stat) {
                    return stat('table').eq(table('id')).and(stat.hasFields('storage_engine'));
                  }).without('id', 'table', 'db'), function (replicaRow, statRow) {
                    return replicaRow('server').eq(statRow('server'));
                  }).zip().coerceTo('array')
                };
              });
            }).coerceTo('array')
          };
        });
      }).coerceTo("array")
                                                                                                                                                                                                                     ^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^ ^^^^^^^^^^ ^^^^^^                   
    at RqlRuntimeError.RqlServerError (/Users/test/test/node_modules/rethinkdb/errors.js:39:13)
    at new RqlRuntimeError (/Users/test/test/node_modules/rethinkdb/errors.js:51:50)
    at mkErr (/Users/test/test/node_modules/rethinkdb/util.js:173:10)
    at TcpConnection.Connection._processResponse (/Users/test/test/node_modules/rethinkdb/net.js:138:16)
    at TcpConnection.Connection._data (/Users/test/test/node_modules/rethinkdb/net.js:104:12)
    at Socket.<anonymous> (/Users/test/test/node_modules/rethinkdb/net.js:495:32)
    at emitOne (events.js:75:13)
    at Socket.emit (events.js:150:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at TCP.onread (net.js:510:20)
From previous event:
    at CoerceTo.TermBase.run (/Users/test/test/node_modules/rethinkdb/ast.js:131:12)
    at file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:2737:27
From previous event:
    at getTables (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:2719:23)
    at Database.<anonymous> (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:2793:15)
    at Database.getTables (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:2781:28)
    at file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:570:19
    at processImmediate [as _immediateCallback] (timers.js:321:17)
From previous event:
    at connect (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:559:9)
    at Object.executeDispatch (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:18453:22)
    at SimpleEventPlugin.executeDispatch (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:30422:41)
    at forEachEventDispatch (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:18441:6)
    at Object.executeDispatchesInOrder (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:18462:4)
    at executeDispatchesAndRelease (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:50334:23)
    at Array.forEach (native)
    at forEachAccumulated (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:56988:10)
    at Object.EventPluginHub.processEventQueue (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:50541:6)
    at runEventQueueInBatch (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:53472:19)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:53498:6)
    at handleTopLevelImpl (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:29550:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:51344:21)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:28508:20)
    at Object.batchedUpdates (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:31933:21)
    at ReactEventListener.dispatchEvent (file:///Users/test/test/build/test/osx64/test.app/Contents/Resources/app.nw/js/app.js:29644:21)
```

Doing some debugging, when running normally the `_sendQuery` method sends the following JSON:

```json
[
  1,
  [
    51,
    [
      [
        38,
        [
          [
            72,
            [
              [
                50,
                [
                  [
                    15,
                    [
                      [
                        14,
                        [
                          "rethinkdb"
                        ]
                      ],
                      "table_config"
                    ],
                    {
                      "identifier_format": "uuid"
                    }
                  ],
                  "id",
                  [
                    15,
                    [
                      [
                        14,
                        [
                          "rethinkdb"
                        ]
                      ],
                      "table_status"
                    ],
                    {
                      "identifier_format": "uuid"
                    }
                  ]
                ]
              ]
            ]
          ],
          [
            69,
            [
              [
                2,
                [
                  0
                ]
              ],
              [
                35,
                [
                  [
                    10,
                    [
                      0
                    ]
                  ],
                  [
                    69,
                    [
                      [
                        2,
                        [
                          1
                        ]
                      ],
                      {
                        "shards": [
                          51,
                          [
                            [
                              38,
                              [
                                [
                                  170,
                                  [
                                    [
                                      10,
                                      [
                                        1
                                      ]
                                    ],
                                    "shards"
                                  ]
                                ],
                                [
                                  69,
                                  [
                                    [
                                      2,
                                      [
                                        2
                                      ]
                                    ],
                                    [
                                      35,
                                      [
                                        [
                                          10,
                                          [
                                            2
                                          ]
                                        ],
                                        [
                                          69,
                                          [
                                            [
                                              2,
                                              [
                                                3
                                              ]
                                            ],
                                            {
                                              "replicas": [
                                                51,
                                                [
                                                  [
                                                    72,
                                                    [
                                                      [
                                                        48,
                                                        [
                                                          [
                                                            170,
                                                            [
                                                              [
                                                                10,
                                                                [
                                                                  3
                                                                ]
                                                              ],
                                                              "replicas"
                                                            ]
                                                          ],
                                                          [
                                                            34,
                                                            [
                                                              [
                                                                39,
                                                                [
                                                                  [
                                                                    15,
                                                                    [
                                                                      [
                                                                        14,
                                                                        [
                                                                          "rethinkdb"
                                                                        ]
                                                                      ],
                                                                      "stats"
                                                                    ],
                                                                    {
                                                                      "identifier_format": "uuid"
                                                                    }
                                                                  ],
                                                                  [
                                                                    69,
                                                                    [
                                                                      [
                                                                        2,
                                                                        [
                                                                          4
                                                                        ]
                                                                      ],
                                                                      [
                                                                        67,
                                                                        [
                                                                          [
                                                                            17,
                                                                            [
                                                                              [
                                                                                170,
                                                                                [
                                                                                  [
                                                                                    10,
                                                                                    [
                                                                                      4
                                                                                    ]
                                                                                  ],
                                                                                  "table"
                                                                                ]
                                                                              ],
                                                                              [
                                                                                170,
                                                                                [
                                                                                  [
                                                                                    10,
                                                                                    [
                                                                                      1
                                                                                    ]
                                                                                  ],
                                                                                  "id"
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ],
                                                                          [
                                                                            32,
                                                                            [
                                                                              [
                                                                                10,
                                                                                [
                                                                                  4
                                                                                ]
                                                                              ],
                                                                              "storage_engine"
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ],
                                                              "id",
                                                              "table",
                                                              "db"
                                                            ]
                                                          ],
                                                          [
                                                            69,
                                                            [
                                                              [
                                                                2,
                                                                [
                                                                  5,
                                                                  6
                                                                ]
                                                              ],
                                                              [
                                                                17,
                                                                [
                                                                  [
                                                                    170,
                                                                    [
                                                                      [
                                                                        10,
                                                                        [
                                                                          5
                                                                        ]
                                                                      ],
                                                                      "server"
                                                                    ]
                                                                  ],
                                                                  [
                                                                    170,
                                                                    [
                                                                      [
                                                                        10,
                                                                        [
                                                                          6
                                                                        ]
                                                                      ],
                                                                      "server"
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ],
                                                  "array"
                                                ]
                                              ]
                                            }
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ],
                            "array"
                          ]
                        ]
                      }
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ],
      "array"
    ]
  ]
]
```

but when it executes in node webkit it only sends the following JSON:

```json
[
  1,
  [
    51,
    [
      [
        38,
        [
          [
            72,
            [
              [
                50,
                [
                  [
                    39,
                    [
                      [
                        15,
                        [
                          [
                            14,
                            [
                              "rethinkdb"
                            ]
                          ],
                          "table_config"
                        ],
                        {
                          "identifier_format": "uuid"
                        }
                      ],
                      {
                        "db": "2c9d502f-4c95-4cd1-9884-c026d445a180"
                      }
                    ]
                  ],
                  "id",
                  [
                    15,
                    [
                      [
                        14,
                        [
                          "rethinkdb"
                        ]
                      ],
                      "table_status"
                    ],
                    {
                      "identifier_format": "uuid"
                    }
                  ]
                ]
              ]
            ]
          ],
          null
        ]
      ],
      "array"
    ]
  ]
]
```

I'm guessing there's some sort of difference in the node environment that the rethinkdb driver isn't expecting, as it doesn't appear to be building the query correctly before it sends it to the server.

Any hints, tips, pointers, ideas?

### PR DESCRIPTION
**Pull request by jmdobry**
In a few spots the JavaScript driver uses `instanceof` to check for array, function, and object types. As `instanceof` looks at the variable's prototype to find the appropriate constructor, this is a problem when checking a variable that was instantiated in a different JavaScript context, such as an iframe, or in this case the Node Webkit window context. See [Differences of JavaScript contexts](https://github.com/nwjs/nw.js/wiki/Differences-of-JavaScript-contexts).

Using `typeof` (or `Array.isArray` for arrays) is robust to cross-context type checking.

This PR changes three `instancesof` type checks to use `typeof` and one to use `Array.isArray`.

I ran the tests like so `/rethinkdb/test/rql_test/test-runner -i js` and they passed.

### CODE REVIEW

File: drivers/javascript/util.coffee [hunk 1]
```diff
@@ -101,10 +101,10 @@ convertPseudotype = (obj, opts) ->
             obj
 
 recursivelyConvertPseudotype = (obj, opts) ->
-    if obj instanceof Array
+    if Array.isArray obj
```
Comment (jmdobry) [inline drivers/javascript/util.coffee]: Now using `Array.isArray`, like it's used elsewhere in the driver.

File: drivers/javascript/util.coffee [hunk 2]
```diff
@@ -101,10 +101,10 @@ convertPseudotype = (obj, opts) ->
...
         for value, i in obj
             obj[i] = recursivelyConvertPseudotype(value, opts)
-    else if obj instanceof Object
+    else if obj and typeof obj is 'object'
```
Comment (jmdobry) [inline drivers/javascript/util.coffee]: `obj and typeof obj is 'object'` now has two conditions in order to not be fooled by `null`, the `typeof` of which is `"object"`.

**Comment by deontologician** [comment]
Thanks @jmdobry! This looks pretty good, would you mind signing our CLA http://rethinkdb.com/community/cla/ ?

**Comment by jmdobry** [comment]
Done

**Comment by jmdobry** [comment]
Will this be in 2.x, or will it make it into a 1.16.x driver release?

**Comment by deontologician** [comment]
This is currently only on next, which is going for 2.1, but I will backport
it to 2.0. I don't know if we're doing another point release on 1.16 before
2.0 is released

**Comment by danielmewes** [comment]
There won't be any other 1.16 point release, so 2.0 will be enough.

**Comment by jmdobry** [comment]
Do you have any idea what the usage is across the various versions of RethinkDB?

**Comment by deontologician** [comment]
OK, it's on 2.0.x

**Comment by danielmewes** [comment]
@jmdobry we have some data, but I'm not sure what the current numbers are.
2.0 will be supported for longer.
